module.exports = {
  name: "ReactNativeMobileApp",
  slug: "ReactNativeMobileApp",

  extra: {
    REACT_APP_HELLO: process.env.REACT_APP_HELLO,
    REACT_APP_HOST:process.env.REACT_APP_HOST,
    REACT_APP_PORT:process.env.REACT_APP_PORT,

    REACT_APP_STRAVA_CLIENT_SECRET:process.env.REACT_APP_STRAVA_CLIENT_SECRET,
    REACT_APP_STRAVA_REFRESH_TOKEN:process.env.REACT_APP_STRAVA_REFRESH_TOKEN,
    REACT_APP_STRAVA_ACCESS_TOKEN:process.env.REACT_APP_STRAVA_ACCESS_TOKEN,
    REACT_APP_STRAVA_CLIENT_ID:process.env.REACT_APP_STRAVA_CLIENT_ID,
    REACT_APP_STRAVA_REDIRECT_URI:process.env.REACT_APP_STRAVA_REDIRECT_URI,
    REACT_APP_SESSION_SECRET:process.env.REACT_APP_SESSION_SECRET,
    REACT_APP_HELLO:process.env.REACT_APP_HELLO,
    EXPO_STRAVA_CLIENT_SECRET:process.env.EXPO_STRAVA_CLIENT_SECRET
  }
};
